title: Groups
modelClass: Mavitm\Swiper\Models\Group
list: $/mavitm/swiper/models/group/columns.yaml
recordUrl: 'mavitm/swiper/groups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '100'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
